spring:
    application.name: discovery-server
    
server.port: 8082
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka
        register-with-eureka: false
        fetch-registry: false