spring:
  application:
    name: gateway-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka
  instance:
    hostname: localhost

management.endpoints.web.exposure.include: '*'