spring:
  application:
    name: gateway-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance.preferIpAddress: true
