spring:
  application:
    name: gateway-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    hostname: localhost

zuul:
  ignoredServices: '*'
  routes:
    book-service:
      path: /books/**
      serviceId: book-service
    rating-service:
      path: /ratings/**
      serviceId: rating-service

management.endpoints.web.exposure.include: '*'